### ISSUE TITLE
Setting Vim's filetype

### ISSUE THREAD

**Issue by VAggrippino** [RisingOrange/anki-external-editor#3]
I use another plugin along with External Editor that processes the field as Markdown instead of HTML. I thought I could set the filetype by configuring the external editor plugin like this:

```json
{
    "editor": "vim -gf -c 'set filetype=markdown'",
    "shortcut": "Ctrl+Meta+X"
}
```

I've tried every variation of quotes and escaped quotes or spaces that I could think of, but I can't get the editor to open with a markdown filetype the way it does on the command line.  Is there a way to do this with External Editor?

**Comment by RisingOrange** [comment]
Your configuration should now work as it is, I uploaded an update for the add-on on AnkiWeb.
