### ISSUE TITLE
Simplify debugging/improve documentation

### ISSUE THREAD

**Issue by SamuelSwartzberg** [RisingOrange/anki-external-editor#4]
I found It quite hard to get this addon to work, for several interlocking reasons:
- As with other keyboard shortcut addons, on mac `Ctrl` is actually `Cmd`, and `Cmd` does nothing.
- Various editors may not work, presumably due to `$PATH`/config issues.
- There is no information if calling the editor failed, or if the keyboard shortcut didn't even register.

Suggestions:
- Mention the mac `Cmd/Ctrl` issue in the documentation/addon config window.
- Throw an error (ideally in GUI form, e.g. one of those alert windows) if executing the command failed
- Potentially allow specifying a custom environment file, "$PATH", or just mention that the program only reads from the default locations (if this is indeed so), and how that might interact with custom installs, e.g. via Homebrew.

Anecdotally, the addon did also not seem to work under 2.1.49, but since updating anki was one of the first steps I did when debugging, I can't be sure that it wasn't one of the above issues instead.

Just a few things that would clear up some of the confusion that also some of the other negative reviews seem to be suffering from. Thanks for developing the addon, and cheers! :)

**Comment by SamuelSwartzberg** [comment]
Also, it seems you have to use `-w` with `code`, so it seems the current implementation requires the command to wait until exit. If so, might also be good to mention that.

**Comment by SamuelSwartzberg** [comment]
Thanks for the quick answer and the changes! One minor misunderstanding seems to have happened regarding ctrl/cmd on mac: Specifying `cmd` as a shortcut in the config file does nothing, specifying `ctrl` actually means you need to press `cmd` (and thus there is also no way to specify `ctrl`, which does also exist on the mac keyboard). So with the changed default, the shortcut won't work at all. Instead, I think it would be better to keep the default and instead display some text that states the above, so people won't try to use `cmd` in their custom shortcuts (which won't work) and know to press cmd if the shortcut contains `ctrl`. I hope that makes it more clear!

**Comment by RisingOrange** [comment]
Thanks again! You can now specify a shortcut containing the cmd key and it will work because the add-on replaces it internally with ctrl. The config window information now also says that you can't use ctrl in shortcuts on Mac. I think this should be a good solution.

**Comment by SamuelSwartzberg** [comment]
Nice, sounds good!
