### ISSUE TITLE
Add option to set extension of temporary files

### ISSUE THREAD

**Issue by SamuelSwartzberg** [RisingOrange/anki-external-editor#5]
Basically, my anki flashcards are actually markdown(-like) files, so I have to switch the language to md manually in vscode whenever I open a card to edit. This is but a minor hassle, and perhaps something I could solve in vscode itself, but I thought it might be nice if the addon included a function to pick the extension of the temporary files oneself. :)
This is a very niche use-case, so feel free to close this as wontfix it if you want!

**Comment by RisingOrange** [comment]
I added a file extension option and updated the add-on on AnkiWeb. :)

**Comment by ghost** [comment]
It works! Thanks, you're the best! <3
